### ISSUE TITLE
Question regarding sense signal & record LED

### ISSUE THREAD

**Issue by Pentasis** [sweetlilmre/TapuinoNext#10]
Hi, sorry for asking this here.
I am currently building (well, designing for now) a tapuino into an old 1530 case. I want to keep it as original as possible, so I put the display and the sd-card into the tape-lid and reuse the original buttons (which is a bit of a challenge).

I also want the counter to actually work (just because), so I intend to put a small motor in there. I'm still in the design-stage so don't have the actual parts yet. I want it to turn only when reading/writing. Is the sense-signal suitable for that? Is it continuously on while reading/writing? Also, is it 5V?

Also, I assume the record_LED only works when recording (writing) not reading, right? As a feature request, could a read_LED be implemented? (In the end I will probably use a multi-colour-led as a replacement for the original one and have it switch colours depending on power/read/write)

**Comment by sweetlilmre** [comment]
Hi there,

SENSE is activated on the datasette by pressing PLAY (or record and play). IIRC it will be on for the duration, although there are cases where  SENSE will be active but the motor has stopped (game has finished loading). As I have the correct formula for calculating the counter, I would suggest replacing the analogue counter with a digital one and we could look at some digital interface to communicate the value (I2C perhaps?). A small oled screen or very small I2C 3-digit 7 segment display could be awesome for this.

As for LEDs, there are plenty of pins available so I could add read and/or write LEDS, something I had meant to do.

How are you building the TapuinoNext? On breadboard or using the reference PCB? I might need to change some pin assignments if I'm going to add further LEDs or a counter interface to the code and will then need to update the schematic if you are using the PCB.

**Comment by sweetlilmre** [comment]
Closing this issue as no response from OP.
