### ISSUE TITLE
TAP recording on VIC 20

### ISSUE THREAD

**Issue by sweetlilmre** [sweetlilmre/TapuinoNext#2]
There seems to be something wrong with this. Generated TAP files do not parse in VICE.  
I am working with a user to resolve this (unfortunately I do not own a VIC20) and will update the issue with detail as it is discovered.

Previously recording was tested on a C64 using ABC-Turbo II loader from a 1541-II Ultimate cartridge and this was working well.

I will repeat this test as soon as possible.

**Comment by predecker** [comment]
I downgraded to release ...38 and that version loaded the frogger.tap I sent you.
And ... :-) ... it loaded my recorded tap from the ... 122 version. So "record" works in 122 and "load" in 38.

**Comment by sweetlilmre** [comment]
I've managed to get to the root cause of this and have a fix that seems to work for all current IDF versions.

See: espressif/arduino-esp32#6693

Thanks for the help!
